organization: 'sallys-shoes'
username: 'sally'
repo: 'shoe-sorter'
use_password: false
milestone: 'Redesign' # Optional
password: '' # Optional
authkey: 'awdhZPBmUhV7C8KTvTXoqPrCYBfKrptqmPT6Z7Jk' # Optional
output_csv: './output_csvs/shoe-sorter-issues.csv' # Optional